DROP TABLE IF EXISTS returned_items;

DROP TABLE IF EXISTS order_items;

DROP TABLE IF EXISTS orders;

DROP TABLE IF EXISTS products;

DROP TABLE IF EXISTS customers;

DROP DATABASE IF EXISTS abc_shop;
